# Generated by Django 3.2.16 on 2023-07-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20230706_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='vacancies',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
