# Generated by Django 3.2.16 on 2023-07-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_joblisting_vacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobseeker/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employer/'),
        ),
    ]
