# Generated by Django 3.2.16 on 2023-07-08 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0005_auto_20230708_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='email',
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(auto_now_add=True)),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.employee')),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.joblisting')),
            ],
        ),
    ]
