# Generated by Django 3.2.16 on 2023-07-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_employer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='job_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.joblisting'),
        ),
    ]
