# Generated by Django 3.2.16 on 2023-07-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20230712_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
